### ISSUE TITLE
question: how to pull from and how to push to this local registry?

### ISSUE THREAD

**Issue by avkonst** [dhovart/cargo-local-registry#169]
Hi,

Thanks for the useful tool.

Let's say I have 1 project which builds a library. I would like to publish it to a local registry first, and after refer to this library in the second project. How can I achieve it?

**Comment by dhovart** [comment]
Hi!
You need to generate a Cargo.lock file that points to your local package, and then run `cargo local-registry --sync path/to/Cargo.lock path/to/registry` as specified in the README.

To pull from your registry locally you need first to add a new registry in your cargo config of type `local-registry`. Check cargo configuration documentation: https://doc.rust-lang.org/cargo/reference/config.html#sourcenamelocal-registry

You then need to specify from which registry to pull. See https://doc.rust-lang.org/cargo/reference/registries.html#using-an-alternate-registry
