### ISSUE TITLE
Allow namespaced features without nightly now they are stabilised

### ISSUE THREAD

**Issue by jarhodes314** [dhovart/cargo-local-registry#171]
#168 removes dependencies from namespaced features, but these are now available in stable Rust. As a result, there is currently no way of downloading a crate with namespaced features (e.g. https://github.com/seladb/pickledb-rs).

**Comment by dhovart** [comment]
I've merged https://github.com/dhovart/cargo-local-registry/pull/170 who adresses this. Releasing a new version soon.
