### ISSUE TITLE
Cannot sync sparse registries

### ISSUE THREAD

**Issue by Jake-Shadle** [dhovart/cargo-local-registry#181]
This crate currently uses cargo 1.69.1, and thus fails with

```
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to get `crate-one` as a dependency of package `yank-check v0.1.0 (/home/jake/code/cargo-deny/examples/12_yank_check)`

Caused by:
  failed to load source for dependency `crate-one`

Caused by:
  Unable to update registry `embark-deny-sparse`

Caused by:
  Usage of HTTP-based registries requires `-Z http-registry`
```

when there is a sparse HTTP registry present. This is possible to enable via the [unstable](https://doc.rust-lang.org/cargo/reference/unstable.html#unstable-features) table in .cargo/config.toml so that this crate works, but that's a bit tedious when I think it just needs to be updated to use 1.70+ to enable sparse HTTP registries without needing to tweak anything.

**Comment by dhovart** [comment]
Hi, I've just updated the cargo dependency to the latest version. Le me know if it's better for you.

**Comment by Jake-Shadle** [comment]
I assume it works now, forgot this issue was open, apologies.
