### ISSUE TITLE
cannot download crate package from github

### ISSUE THREAD

**Issue by miaomiao1992** [dhovart/cargo-local-registry#183]
cargo local-registry
this command seems cannot download crate package from github

**Comment by miaomiao1992** [comment]
if one cargo project depend on another project called bof which url is githubxxx, the command seems cannot download crate package of project b from github

**Comment by dhovart** [comment]
Hi, could you please provide a reproducible example?

**Comment by miaomiao1992** [comment]
sorry,i made a mistake.
i tried again,and crate package always can be downloaded from github

**Comment by miaomiao1992** [comment]
> Hi, could you please provide a reproducible example?

please close this issue. 

this project is very good !

**Comment by dhovart** [comment]
No problem :)
